name: shortcake_app
description: Shortcake frontend
version: 0.0.1
homepage: https://github.com/shortcake-dev/shortcake-app
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

  # GraphQL
  ferry: ^0.10.4
  ferry_flutter: ^0.5.4
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0
  built_collection: ^5.0.0

  # Page navigation
  beamer: ^0.13.2

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1

  # For ferry
  ferry_generator: ^0.4.4
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
