name: shortcake_app
description: Shortcake frontend
version: 0.0.1
homepage: https://github.com/shortcake-dev/shortcake-app
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shortcake: ^0.0.2-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

