name: tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  flutter-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter config --no-analytics
      - run: flutter format --dry-run --set-exit-if-changed .
