name: tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: |
          flutter test \
            --coverage \
            --reporter expanded \
            --test-randomize-ordering-seed random
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage/
      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
