name: tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter pub build_runner build
      - run: flutter test --reporter expanded
